name: SSH Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSHpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy via SSH
        env:
#          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_PASSWORD: G3x@9P!sT#7mQd
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@103.83.89.237 -P8008 "mkdir majidtest"
